apps/DragonOathApp/urls/urls.py
from django.urls import path
from DragonOathApp import views

app_name = 'dragonapp'

urlpatterns = [
    path('login/', views.login_view, name='login-page'),
    path('register/', views.register_view, name='register-page'),
    path('index/', views.index_view, name='index-page'),
    path('authors/', views.authors_view, name='authors-page'),
    path('author/<int:pk>/', views.author_view, name='author-page'),
    path('books/', views.books_view, name='books-page'),
    path('book/<int:pk>/', views.book_view, name='book-page'),
    path('foreignAuthor/', views.foreign_author, name='foreignAuthor-page'),
    path('test/', views.test, name='test-page'),
    path('holmes/', views.holmes_view, name='holmes-page'),
    path('holmes/<int:pk>/', views.holmes_view_pk, name='holmes-pk-page'),
    path('original/', views.original_view, name='original-page')
]

drfAPI/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

api_urlpatterns = [
    path('dragonapp/', include('DragonOathApp.urls.api_urls', namespace='dragonapi'))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(api_urlpatterns)),
    path('dragonapp/', include('DragonOathApp.urls.urls', namespace='dragonapp'))
]

urlpatterns += api_urlpatterns

apps/DragonOathApp/models.py
from django.db import models

# Create your models here.

class Mark(models.Model):
    mark = models.CharField(max_length=2, verbose_name='字母')

    class Meta:
        db_table = 'django_mark'
        verbose_name = '字母'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.mark

class ForeignAuthor(models.Model):
    author = models.CharField(max_length=32, verbose_name='作者')
    brief = models.TextField(verbose_name='简介')
    mark = models.ForeignKey(Mark, on_delete=models.CASCADE, verbose_name='字母')

    def __str__(self):
        return self.author

class BooksInfo(models.Model):
    book_name = models.CharField(max_length=32, verbose_name="书名")
    content = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'django_books'
        verbose_name = '书籍'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.book_name

class Userinfo(models.Model):
    user_name = models.CharField(max_length=10, verbose_name='账号')
    passwd = models.CharField(max_length=32, verbose_name='密码')
    gmail = models.EmailField(null=False, unique=True)

    # roles = models.ForeignKey('RoleInfo', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        db_table = 'django_users'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_name

class Author(models.Model):
    author_name = models.CharField(max_length=10, verbose_name='作家')
    brief = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'django_author'
        verbose_name = '作者'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.author_name


class Pageview(models.Model):
    read = models.IntegerField(verbose_name='阅读量', blank=True, null=True)
    comments = models.IntegerField(verbose_name='评论数', blank=True, null=True)
    book = models.ForeignKey(BooksInfo, on_delete=models.CASCADE, verbose_name='书籍', blank=True, null=True)

    class Meta:
        db_table = 'django_pageview'
        verbose_name = '阅读量'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.read

class Roleinfo(models.Model):
    definition = (
        ("dps", "DPS"),
        ("tank", "TANK"),
        ("healer", "healer")
    )
    gender = (
        ("gentleman", "gentleman"),
        ("madam", "madam")
    )
    role_class = models.CharField(choices=definition, default="dps", verbose_name="职业", max_length=10)
    role_gender = models.CharField(choices=gender, default="gentleman", verbose_name="性别", max_length=10)
    role_name = models.CharField(max_length=10, verbose_name="角色名")
    role_user = models.ForeignKey(Userinfo, on_delete=models.CASCADE, verbose_name='用户')

    class Meta:
        db_table = 'django_roles'
        verbose_name = '角色'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.role_name

class Holmes(models.Model):
    book_name = models.CharField(max_length=32, verbose_name='书名')
    content = models.TextField(verbose_name='内容')
    book = models.ForeignKey(BooksInfo, on_delete=models.CASCADE, verbose_name='书籍ID')

    class Meta:
        db_table = 'django_holmes'
        verbose_name = '福尔摩斯'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.book_name

apps/DragonOathApp/views.py
from django.shortcuts import render, redirect
from .froms import LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def original_view(request):
    return render(request, 'dragonapp/original.html')

def holmes_view_pk(request, pk):
    return render(request, 'dragonapp/holmes-pk.html')

def holmes_view(request):
    return render(request, 'dragonapp/holmes.html')

def login_view(request):
    user_form = LoginForm()

    content = {
        'user_form': user_form
    }
    return render(request, 'dragonapp/login.html', content)

def register_view(request):
    return render(request, 'dragonapp/register.html')

def index_view(request):
    return render(request, 'dragonapp/index.html')

def authors_view(request):
    return render(request, 'dragonapp/authors.html')

def author_view(request, pk):
    return render(request, 'dragonapp/author.html')

def books_view(request):
    return render(request, 'dragonapp/books.html')

def book_view(request, pk):
    return render(request, 'dragonapp/book.html')

def foreign_author(request):
    return render(request, 'dragonapp/foreignAuthor.html')

def test(request):
    return render(request, 'dragonapp/test.html')

apps/DragonOathApp/templates/dragonapp/author.html
{% extends 'html_base.html' %}

apps/DragonOathApp/templates/dragonapp/authors.html
{% extends 'html_base.html' %}
{% load static %}
{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/author_css.css' %}">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="authorBox">
                    <h1 class="ml-lg-5">作家</h1>
                    <ul id="aul" class="cul"></ul>
                    <ul class="pagination">
                        <li class="page-item"><button class="page-link" id="pageA">1</button></li>
                        <li class="page-item"><button class="page-link" id="pageB">2</button></li>
                        <li class="page-item"><button class="page-link" id="pageC">3</button></li>
                    </ul>
                </div>
            </div>
            <div class="col-3">
                <div class="container-fluid">
                    <div class="row">
                        <div  id="br" style='white-space:pre-wrap; width:900px;'></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        var removeAulElement = ()=>{
            var aulId = document.getElementById('aul')
            while(aulId.hasChildNodes()){
                aulId.removeChild(aulId.firstChild)
            }
        }

        var defaultHtml = ()=>{
            removeAulElement()
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/author/',
                success: (data)=>{
                    for(var i=0;i<30;i++){
                        var li = document.createElement('li')
                        var a = document.createElement('a')
                        li.setAttribute("id", 'li'+i)
                        li.setAttribute("class", 'lic')
                        li.setAttribute("style", 'list-style-type:none; float: left;\n' +
                                                 'width: 33%;\n' +
                                                 'margin-bottom: 20px;\n' +
                                                 'line-height: 20px; ')
                        a.setAttribute("id", 'a' + i)
                        a.setAttribute("href", "http://127.0.0.1/dragonapp/author/"+data[i].id+"/")
                        document.getElementById('aul').appendChild(li)
                        document.getElementById('li'+i).appendChild(a)
                        document.getElementById('a'+i).innerHTML = data[i].author_name
                        const n = data[i].id
                        document.getElementById('a'+i).onmouseover = ()=>{
                            $.ajax({
                                url: 'http://127.0.0.1/api/v1/dragonapp/author/'+n+'/',
                                type: 'GET',
                                success:(data)=>{
                                    document.getElementById('br').innerHTML = data.brief
                                }
                            })
                        }
                    }
                }
            })
        }

        $(document).ready = defaultHtml()

        $('#pageA').click(()=>{
            removeAulElement()
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/author/',
                success: (data)=>{
                    for(var i=0;i<30;i++){
                        var li = document.createElement('li')
                        var a = document.createElement('a')
                        li.setAttribute("id", 'li'+i)
                        li.setAttribute("class", 'lic')
                        li.setAttribute("style", 'list-style-type:none; float: left;\n' +
                                                 'width: 33%;\n' +
                                                 'margin-bottom: 20px;\n' +
                                                 'line-height: 20px; ')
                        a.setAttribute("id", 'a' + i)
                        a.setAttribute("href", "http://127.0.0.1/dragonapp/author/"+data[i].id+"/")
                        document.getElementById('aul').appendChild(li)
                        document.getElementById('li'+i).appendChild(a)
                        document.getElementById('a'+i).innerHTML = data[i].author_name
                        const n = data[i].id
                        document.getElementById('a'+i).onmouseover = ()=>{
                            $.ajax({
                                url: 'http://127.0.0.1/api/v1/dragonapp/author/'+n+'/',
                                type: 'GET',
                                success:(data)=>{
                                    document.getElementById('br').innerHTML = data.brief
                                }
                            })
                        }
                    }
                }
            })
        })

        $('#pageB').click(()=>{
            removeAulElement()
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/author/',
                success: (data)=>{
                    for(var i=30;i<60;i++){
                        var li = document.createElement('li')
                        var a = document.createElement('a')
                        li.setAttribute("id", 'li'+i)
                        li.setAttribute("class", 'lic')
                        li.setAttribute("style", 'list-style-type:none')
                        a.setAttribute("id", 'a' + i)
                        a.setAttribute("href", "http://127.0.0.1/dragonapp/author/"+data[i].id+"/")
                        document.getElementById('aul').appendChild(li)
                        document.getElementById('li'+i).appendChild(a)
                        document.getElementById('a'+i).innerHTML = data[i].author_name
                        const n = data[i].id
                        document.getElementById('a'+i).onmouseover = ()=>{
                            $.ajax({
                                url: 'http://127.0.0.1/api/v1/dragonapp/author/'+n+'/',
                                type: 'GET',
                                success:(data)=>{
                                    document.getElementById('br').innerHTML = data.brief
                                }
                            })
                        }
                    }
                }
            })
        })

        $('#pageC').click(()=>{
            removeAulElement()
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/author/',
                success: (data)=>{
                    for(var i=60;i<data.length;i++){
                        var li = document.createElement('li')
                        var a = document.createElement('a')
                        li.setAttribute("id", 'li'+i)
                        li.setAttribute("class", 'lic')
                        li.setAttribute("style", 'list-style-type:none')
                        a.setAttribute("id", 'a' + i)
                        a.setAttribute("href", "http://127.0.0.1/dragonapp/author/"+data[i].id+"/")
                        document.getElementById('aul').appendChild(li)
                        document.getElementById('li'+i).appendChild(a)
                        document.getElementById('a'+i).innerHTML = data[i].author_name
                        const n = data[i].id
                        document.getElementById('a'+i).onmouseover = ()=>{
                            $.ajax({
                                url: 'http://127.0.0.1/api/v1/dragonapp/author/'+n+'/',
                                type: 'GET',
                                success:(data)=>{
                                    document.getElementById('br').innerHTML = data.brief
                                }
                            })
                        }
                    }
                }
            })
        })
    </script>
{% endblock %}

apps/DragonOathApp/templates/dragonapp/book.html
{% extends 'html_base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div id="book-box" style="background-color: #22ff59">
                    <h1 id="bookTitle"></h1>
                    <p id="book-content" style='white-space:pre-wrap; width:900px;'></p>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script>
        var url = window.location.href;
        var urlid = url.split('/')[5]
        $(document).ready(()=> {
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/pageview/'+urlid + '/',
                success:(data)=>{
                    var n = parseInt(data.read) + 1
                    $.ajax({
                        type: 'PUT',
                        url: 'http://127.0.0.1/api/v1/dragonapp/pageview/' + urlid + '/',
                        data:{'read': n},
                        success:(data)=>{
                            console.log(data.read)
                            }
                        })
                    }
                })
            $.ajax({
                url: 'http://127.0.0.1/api/v1/dragonapp/apibooks/' + urlid + '/',
                type: 'GET',
                success: (data) => {
                    var end = 2000
                    var totalEnd = data.content.length
                    document.getElementById('bookTitle').innerHTML = data.book_name + '：'
                    document.getElementById('book-content').innerHTML += data.content.substring(0, end)
                    $(window).scroll(()=>{
                        var scrollTop = $(this).scrollTop()
                        var scrollHeight = $(document).height()
                        var windowHeight = $(this).height()
                        if(scrollTop + windowHeight == scrollHeight){
                            document.getElementById('book-content').innerHTML += data.content.substring(end, end+end)
                            end += end
                        }
                    })
                }
            })
        })
        {#$(document).ready(()=> {#}
        {#    $.ajax({#}
        {#        url: 'http://127.0.0.1/api/v1/dragonapp/pageview/' + urlid + '/',#}
        {#        type: 'GET',#}
        {#        success: (data) => {#}
        {#            const n = data.read#}
        {#            $.ajax({#}
        {#                url: 'http://127.0.0.1/api/v1/dragonapp/pageview/' + urlid + '/',#}
        {#                type: 'PUT',#}
        {#            })#}
        {#        }#}
        {#    })#}
        {#)#}
    </script>
{% endblock %}

apps/DragonOathApp/templates/dragonapp/books.html
{% extends 'html_base.html' %}
{% load static %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/holmes_css.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="authorBox">
                    <h1 class="ml-lg-5">推理短篇</h1>
                    <ul id="aul" class="cul"></ul>
                    <ul class="pagination" id="paginationId"></ul>
                </div>
            </div>
            <div class="col-3">
                <div class="container-fluid">
                    <div class="row">
                        <div  id="br"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        var removeAulElement = ()=>{
            var aulId = document.getElementById('aul')
            while(aulId.hasChildNodes()){
                aulId.removeChild(aulId.firstChild)
            }
        }
        var defaultHtml = ()=>{
            removeAulElement()
            $.ajax({
                type: 'GET',
                url: 'http://127.0.0.1/api/v1/dragonapp/apibooks/',
                success: (data)=>{
                    for(var i=0;i<30;i++){
                        var li = document.createElement('li')
                        var a = document.createElement('a')
                        li.setAttribute("id", 'li'+i)
                        li.setAttribute("class", 'lic')
                        li.setAttribute("style", 'list-style-type:none; float: left;\n' +
                                                 'width: 33%;\n' +
                                                 'margin-bottom: 20px;\n' +
                                                 'line-height: 20px;')
                        a.setAttribute("id", 'a' + i)
                        a.setAttribute('class', 'ac')
                        a.setAttribute("href", "http://127.0.0.1/dragonapp/book/"+data[i].id+"/")
                        document.getElementById('aul').appendChild(li)
                        document.getElementById('li'+i).appendChild(a)
                        document.getElementById('a'+i).innerHTML = data[i].book_name
                        }
                    }
                })
            }
        var isAnim = false
        $(document).ready(()=>{
            $.ajax({
                url: 'http://127.0.0.1/api/v1/dragonapp/apibooks/',
                type: 'GET',
                success(data){
                    var pageNum = Math.ceil(data.length/30)
                    for(var i = 0; i<pageNum; i++){
                        let n = i
                        var li = document.createElement('li')
                        var btn = document.createElement('button')
                        li.setAttribute('class', "page-item")
                        li.setAttribute('id', "li"+i)
                        btn.setAttribute('class', "page-link")
                        btn.setAttribute('id', "page"+i)
                        btn.innerHTML = i + 1
                        document.getElementById('paginationId').appendChild(li)
                        document.getElementById('li'+i).appendChild(btn)
                        if(!isAnim){
                            defaultHtml()
                            isAnim = true
                        }
                        document.getElementById('page'+n).onclick = ()=>{
                            removeAulElement()
                            var j = n+1
                            for(var k = j*30-30; k<j*30; k++){
                                var li = document.createElement('li')
                                var a = document.createElement('a')
                                li.setAttribute("id", 'li'+k)
                                li.setAttribute("class", 'lic')
                                li.setAttribute("style", 'list-style-type:none; float: left;\n' +
                                                         'width: 33%;\n' +
                                                         'margin-bottom: 20px;\n' +
                                                         'line-height: 20px; ')
                                a.setAttribute("id", 'a' + k)
                                a.setAttribute('class', 'ac')
                                a.setAttribute("href", "http://127.0.0.1/dragonapp/book/"+data[k].id+"/")
                                document.getElementById('aul').appendChild(li)
                                document.getElementById('li'+k).appendChild(a)
                                document.getElementById('a'+k).innerHTML = data[k].book_name
                            }
                        }
                    }
                }
            })
        })
    </script>
{% endblock %}

apps/DragonOathApp/templates/dragonapp/foreignAuthor.html
{% extends 'html_base.html' %}

apps/DragonOathApp/templates/dragonapp/login.html
{#{% extends 'html_base.html' %}#}
{#{% load static %}#}
{##}
{#{% block content %}#}
{#    <div id="logo" style="padding-left: 500px">#}
{#        <a href="{% url 'dragonapp:index-page' %}">#}
{#            <img src="{% static 'imgs/car.png' %}" alt="car" style="width: 5%">#}
{#        </a>#}
{#        <span>静观书林，欢迎登陆</span>#}
{#    </div>#}
{#    <div class="container-fluid">#}
{#        <div class="row">#}
{#            <div class="col-8"></div>#}
{#            <div class="col-4">#}
{#                <div class="card">#}
{#                    <div class="card-header bg-light">#}
{#                        <h3>登陆</h3>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <div></div>#}
{#                        <div class="input-group mb-3">#}
{#                            <div class="input-group-prepend">#}
{#                                <span class="input-group-text">邮&nbsp;&nbsp;&nbsp;&nbsp;箱：</span>#}
{#                            </div>#}
{#                            <input type="email" class="form-control" placeholder="邮箱" id="einput">#}
{#                        </div>#}
{#                        <div class="input-group mb-3">#}
{#                            <div class="input-group-prepend">#}
{#                                <span class="input-group-text">密&nbsp;&nbsp;&nbsp;&nbsp;码：</span>#}
{#                            </div>#}
{#                            <input type="password" class="form-control" placeholder="邮箱" id="pinput">#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="card-footer">#}
{#                        <button class="btn btn-light" id="lbtn">登陆</button>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{##}
{#{% block javascript %}#}
{#    <script>#}
{#        $("#lbtn").click(() =>{#}
{#            $.ajax({#}
{#                type: 'GET',#}
{#                url: 'http://127.0.0.1/api/v1/dragonapp/users/',#}
{#                success: (data)=>{#}
{#                    var einput = document.getElementById('einput').value#}
{#                    var pinput = document.getElementById('pinput').value#}
{#                    for(let k in data){#}
{#                        if(data[k].gmail === einput && data[k].passwd === pinput){#}
{#                            document.location.href='{% url 'dragonapp:index-page' %}'#}
{#                        }else if (data[k].id === data.length){#}
{#                            alert('账号或密码错误')#}
{#                        }#}
{#                    }#}
{#                }#}
{#            })#}
{#        })#}
{#    </script>#}
{#{% endblock %}#}

{% extends 'html_base.html' %}
{% load static %}

{% block content %}
    <div id="logo" style="padding-left: 500px">
        <a href="{% url 'dragonapp:index-page' %}">
            <img src="{% static 'imgs/car.png' %}" alt="car" style="width: 5%">
        </a>
        <span>静观书林，欢迎登陆</span>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <div class="card shadow">
                    <div class="card-header text-center text-light bg-dark">
                        <h3 class="card-title">登录页面</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'dragonapp:login-page' %}" method="get">
                            {% csrf_token %}
                            {{ user_form.as_p }}
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">登陆</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/DragonOathApp/templates/dragonapp/register.html
{% extends 'html_base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-8"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header bg-light">
                        <h3>注册</h3>
                    </div>
                    <div class="card-body">
                        <div></div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">邮&nbsp;&nbsp;&nbsp;&nbsp;箱：</span>
                            </div>
                            <input type="email" class="form-control" placeholder="邮箱" id="einput">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">用户名：</span>
                            </div>
                            <input type="text" class="form-control" placeholder="用&nbsp;&nbsp;户&nbsp;&nbsp;名" id="uinput">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">密&nbsp;&nbsp;&nbsp;&nbsp;码：</span>
                            </div>
                            <input type="password" class="form-control" placeholder="密码" id="mpinput">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">确认密码：</span>
                            </div>
                            <input type="password" class="form-control" placeholder="再次确认密码" id="opinput">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="submit-row" id="sumbit">注册</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $("#sumbit").click(()=>{
            var mpinput = document.getElementById('mpinput').value
            var opinput = document.getElementById('opinput').value
            if(mpinput === opinput){
            var einput = document.getElementById('einput').value
            var uinput = document.getElementById('uinput').value
            $.ajax({
                type: 'POST',
                url: 'http://127.0.0.1/api/v1/dragonapp/users/',
                data: {gmail:einput, user_name:uinput, passwd:mpinput},
                dataType: 'json',
                success: (data)=>{
                    alert('账号注册成功，你可以使用：'+einput+'登陆了！','',(document.location.href='{% url 'dragonapp:login-page' %}'))
                },
                error: ()=>{
                    alert('邮箱已被注册！')
                }
            })
        }else{
                alert('两次输入的密码不一致，请重新输入')
            }
    })
    </script>
{% endblock %}

apps/DragonOathApp/templates/dragonapp/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'Vue/vue.js' %}"></script>
</head>
<body>
    <div id="app">
        aaa
        {{msg}}
    </div>
    <script>
        {#var data = {a: 1}#}
        var vm = new Vue({
            el: '#app',
            data: {msg: 'hi vue'},
            created: function(){
                console.log('a is '+ this.msg)
            }
        })
    </script>
</body>
</html>

apps/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand"  href="{% url 'dragonapp:index-page' %}">静观书林</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dragonapp:books-page' %}">短篇小说<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dragonapp:authors-page' %}">著名作者简介</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dragonapp:holmes-page' %}">福尔摩斯全集</a>
      </li>
      <li class="nav-item">
        <a class='nav-link' href="{% url 'dragonapp:original-page' %}">原创投稿</a>
      </li>
    </ul>
    <div class="input-group-prepend">
      <input type="text" class="form-control" id='searchInput'>
      <button type="button" class='btn btn-outline-light col-3'>搜索</button>
    </div>
    <div>&nbsp;&nbsp;</div>
    <div>&nbsp;&nbsp;</div>
    <a href="{% url 'dragonapp:login-page' %}" class="btn text-dark">登陆</a>&nbsp;&nbsp;<a href="{% url 'dragonapp:register-page' %}" class="btn text-dark">注册</a>
  </div>
</nav>
<div id="autoDiv">
    <ul id="ulNav" class="hidden"></ul>
</div>

apps/templates/bootstrap_css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

apps/templates/jquery_js.html
{% load static %}

<script src="{% static 'Jquery-3.5.1/jquery-3.5.1.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>